# Importing Libraries

In [269]:
import pandas as pd
import pickle
import warnings
warnings.filterwarnings("ignore")

# Reading data file

In [270]:
data=pd.read_csv("Cellphone.csv")

In [271]:
data

,Product_id,Price,Sale,weight,resoloution,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness
0,203,2357,10,135.0,5.20,424,8,1.350,16.0,3.000,13.00,8.0,2610,7.4
1,880,1749,10,125.0,4.00,233,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
2,40,1916,10,110.0,4.70,312,4,1.200,8.0,1.500,13.00,5.0,2000,7.6
3,99,1315,11,118.5,4.00,233,2,1.300,4.0,0.512,3.15,0.0,1400,11.0
4,880,1749,11,125.0,4.00,233,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1206,3551,4638,178.0,5.46,538,4,1.875,128.0,6.000,12.00,16.0,4080,8.4
157,1296,3211,8016,170.0,5.50,534,4,1.975,128.0,6.000,20.00,8.0,3400,7.9
158,856,3260,8809,150.0,5.50,401,8,2.200,64.0,4.000,20.00,20.0,3000,6.8
159,1296,3211,8946,170.0,5.50,534,4,1.975,128.0,6.000,20.00,8.0,3400,7.9
160,1131,2536,9807,202.0,6.00,367,8,1.500,16.0,3.000,21.50,16.0,2700,8.4

# data preprocessing

In [272]:
data.describe()

,Product_id,Price,Sale,weight,resoloution,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,675.559006,2215.596273,621.465839,170.426087,5.209938,335.055901,4.857143,1.502832,24.501714,2.204994,10.378261,4.503106,2842.111801,8.921739
std,410.851583,768.187171,1546.618517,92.888612,1.509953,134.826659,2.444016,0.599783,28.804773,1.609831,6.181585,4.342053,1366.990838,2.192564
min,10.000000,614.000000,10.000000,66.000000,1.400000,121.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,800.000000,5.100000
25%,237.000000,1734.000000,37.000000,134.100000,4.800000,233.000000,4.000000,1.200000,8.000000,1.000000,5.000000,0.000000,2040.000000,7.600000
50%,774.000000,2258.000000,106.000000,153.000000,5.150000,294.000000,4.000000,1.400000,16.000000,2.000000,12.000000,5.000000,2800.000000,8.400000
75%,1026.000000,2744.000000,382.000000,170.000000,5.500000,428.000000,8.000000,1.875000,32.000000,3.000000,16.000000,8.000000,3240.000000,9.800000
max,1339.000000,4361.000000,9807.000000,753.000000,12.200000,806.000000,8.000000,2.700000,128.000000,6.000000,23.000000,20.000000,9500.000000,18.500000

In [273]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_id    161 non-null    int64
 1   Price         161 non-null    int64
 2   Sale          161 non-null    int64
 3   weight        161 non-null    float64
 4   resoloution   161 non-null    float64
 5   ppi           161 non-null    int64
 6   cpu core      161 non-null    int64
 7   cpu freq      161 non-null    float64
 8   internal mem  161 non-null    float64
 9   ram           161 non-null    float64
 10  RearCam       161 non-null    float64
 11  Front_Cam     161 non-null    float64
 12  battery       161 non-null    int64
 13  thickness     161 non-null    float64
dtypes: float64(8), int64(6)
memory usage: 17.7 KB

In [274]:
data.head()

,Product_id,Price,Sale,weight,resoloution,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness
0,203,2357,10,135.0,5.2,424,8,1.35,16.0,3.000,13.00,8.0,2610,7.4
1,880,1749,10,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9
2,40,1916,10,110.0,4.7,312,4,1.20,8.0,1.500,13.00,5.0,2000,7.6
3,99,1315,11,118.5,4.0,233,2,1.30,4.0,0.512,3.15,0.0,1400,11.0
4,880,1749,11,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9

In [275]:
data.tail()

,Product_id,Price,Sale,weight,resoloution,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness
156,1206,3551,4638,178.0,5.46,538,4,1.875,128.0,6.0,12.0,16.0,4080,8.4
157,1296,3211,8016,170.0,5.50,534,4,1.975,128.0,6.0,20.0,8.0,3400,7.9
158,856,3260,8809,150.0,5.50,401,8,2.200,64.0,4.0,20.0,20.0,3000,6.8
159,1296,3211,8946,170.0,5.50,534,4,1.975,128.0,6.0,20.0,8.0,3400,7.9
160,1131,2536,9807,202.0,6.00,367,8,1.500,16.0,3.0,21.5,16.0,2700,8.4

In [276]:
data.isnull().sum()

Product_id      0
Price           0
Sale            0
weight          0
resoloution     0
ppi             0
cpu core        0
cpu freq        0
internal mem    0
ram             0
RearCam         0
Front_Cam       0
battery         0
thickness       0
dtype: int64

In [277]:
data1=data.drop(["cpu core","cpu freq","ppi"],axis=1)

In [278]:
data1.columns

Index(['Product_id', 'Price', 'Sale', 'weight', 'resoloution', 'internal mem',
       'ram', 'RearCam', 'Front_Cam', 'battery', 'thickness'],
      dtype='object')

In [279]:
y=data1['Price']  #dependent or target variable
X=data1.drop('Price',axis=1)

In [280]:
X

,Product_id,Sale,weight,resoloution,internal mem,ram,RearCam,Front_Cam,battery,thickness
0,203,10,135.0,5.20,16.0,3.000,13.00,8.0,2610,7.4
1,880,10,125.0,4.00,4.0,1.000,3.15,0.0,1700,9.9
2,40,10,110.0,4.70,8.0,1.500,13.00,5.0,2000,7.6
3,99,11,118.5,4.00,4.0,0.512,3.15,0.0,1400,11.0
4,880,11,125.0,4.00,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...
156,1206,4638,178.0,5.46,128.0,6.000,12.00,16.0,4080,8.4
157,1296,8016,170.0,5.50,128.0,6.000,20.00,8.0,3400,7.9
158,856,8809,150.0,5.50,64.0,4.000,20.00,20.0,3000,6.8
159,1296,8946,170.0,5.50,128.0,6.000,20.00,8.0,3400,7.9
160,1131,9807,202.0,6.00,16.0,3.000,21.50,16.0,2700,8.4

In [281]:
y

0      2357
1      1749
2      1916
3      1315
4      1749
       ...
156    3551
157    3211
158    3260
159    3211
160    2536
Name: Price, Length: 161, dtype: int64

# splitting the data

In [282]:
from sklearn.model_selection import train_test_split

In [283]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

# Applying model

In [284]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [285]:
model.fit(X_train,y_train)

LinearRegression()

In [286]:
y_pred=model.predict(X_test)

In [287]:
y_pred

array([1002.88207453, 1941.22845991, 2790.79159414, 1577.45120646,
       1612.39251953, 2033.0108544 , 1003.17882093, 1395.75708757,
       2329.39709616, 2789.45623531, 1328.63301089, 1596.94440105,
       1834.49929883, 3028.72755858, 2045.75789328, 2001.83220614,
       2418.39106216, 3304.46700701, 1595.11748026, 2002.05476595,
       2287.76697262, 1834.4498411 , 2030.10988301, 2442.11417344,
       2780.58783769, 3988.42819517, 2365.78564513, 3331.67544363,
       2481.39803874, 2374.58796482, 3055.6865312 , 2554.04553333,
       2719.74609031, 2852.72007235, 2148.2923712 , 2085.47425955,
       2277.08988304, 1502.73787259, 2287.30354628, 1596.25199277,
       1768.94786583])

In [288]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

#test_size=0.30=r2_score=0.9173404473914227
#test_size=0.35=r2_score=0.9193800921588381

0.918912558539315

In [289]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred,y_test)

39269.936780396085

In [290]:
results=pd.DataFrame(columns=['actual','predicted'])

In [291]:
results['actual']=y_test

In [292]:
results['predicted']=y_pred

In [293]:
results['ID']=results.index
results.head(15)

     actual    predicted   ID
105     833  1002.882075  105
108    1676  1941.228460  108
142    2508  2790.791594  142
55     1777  1577.451206   55
94     1511  1612.392520   94
29     1950  2033.010854   29
101     833  1003.178821  101
51     1347  1395.757088   51
100    2343  2329.397096  100
143    2508  2789.456235  143
19     1238  1328.633011   19
84     1646  1596.944401   84
15     1612  1834.499299   15
66     2746  3028.727559   66
24     1942  2045.757893   24

# Data visualisation

In [297]:
import seaborn as sns

In [298]:
import matplotlib.pyplot as plt

In [299]:
sns.lineplot(x='ID',y='price',data=results.head(50))
sns.lineplot(x='ID',y='predicted',data=results.head(50))

ValueError: Could not interpret value `price` for parameter `y`

# Correlation matrix

In [ ]:
cor_mat=data1.corr()

In [ ]:
cor_mat

In [ ]:
sns.heatmap(cor_mat,vmax=1,vmin=-1,annot=True,linewidth=5,cmap='bwr')

In [ ]:
filename='mobile'
pickle.dump(model,open(filename,'wb'))

In [300]:
new=[[880,10,125.0,4.00,4.0,1.000,3.15,0.0,1700,9.9]]
real=model.predict(new)
real

array([1563.20467543])

## Elastic Regression

In [ ]:
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import ElasticNet

elastic = ElasticNet()

parameters = {'alpha': [1e-15, 1e-10, 1e-8, 1e-4, 1e-3,1e-2, 1, 5, 10, 20]}

elastic_regressor = GridSearchCV(elastic, parameters)

elastic_regressor.fit(X_train, y_train)

In [ ]:
elastic_regressor.best_params_

In [ ]:
elastic=ElasticNet(alpha=.01)
elastic.fit(X_train,y_train)
y_pred_elastic=elastic.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred_elastic)

In [ ]:
elastic_Error=mean_squared_error(y_pred_elastic,y_test)
elastic_Error

In [ ]:
Results= pd.DataFrame(columns=['Actual','Predicted'])
Results['Actual']=y_test
Results['Predicted']=y_pred_elastic
Results=Results.reset_index()
Results['Id']=Results.index
Results.head(10)

In [ ]:
sns.lineplot(x='Id',y='Actual',data=Results.head(50))
sns.lineplot(x='Id',y='Predicted',data=Results.head(50))
plt.plot()